version: '3.8'

services:
  receipt-processor:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    networks:
      - hackaton-net
    entrypoint: ["python", "src/app.py"]
    environment:
      - PYTHONUNBUFFERED=1



networks:
  hackaton-net:
    external: true